### ISSUE TITLE
Fix unit test Test_FixtureAugmentedTestCase_init

### ISSUE THREAD

**Issue by feltech** [TheFoundryVisionmongers/OpenAssetIO#158]
Due to a find-replace error `Test_FixtureAugmentedTestCase_init` is asserting on a mock instance rather than a real instance.

**Comment by foundrytom** [comment]
See https://github.com/TheFoundryVisionmongers/OpenAssetIO/blob/99f12a9f73c61d6d0df8e4f9c6da4035896cfcd3/tests/openassetio/test/manager/test__implementation.py#L127

**Comment by feltech** [comment]
Looks like there isn't actually a bug, just a badly named pytest fixture `mock_test_case` should be `a_test_case`.
