### ISSUE TITLE
Document codebase rules + standards in `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by foundrytom** [TheFoundryVisionmongers/OpenAssetIO#176]
## What

Make sure we have documented coding conventions/rules accordingly

## Why

For obvious reasons :)

**Comment by feltech** [comment]
This issue is still open, despite the parent issue being closed. We have updated the contributing docs several times since this issue was added to "up next", though there is currently no specific mention of `pylint` (which is what the parent issue is about).

**Comment by foundrytom** [comment]
Lets review the standards/documentation once we have the `C` API pattern down, and create new issues for any specific updates.
