### ISSUE TITLE
Core C++: CI

### ISSUE THREAD

**Issue by foundrytom** [TheFoundryVisionmongers/OpenAssetIO#182]
## What

Reinstate CI for existing checks, and ensure best-practice tests are added for the `C`/`C++` codebase. See #181.

## Why

- #183 required us to disable the existing `pytest` checks as they required the built `cpython` `_openassetio` module.
- We need equivalent checks to our `pytest`/`pylint` validation of the Python code base for the `C`/`C++` code base.

## ACs

- Restrict to `linux` for now. Size macOS/Windows as possible
- Opinionated CI check using `clang-format` using the `Google` preset, with line length adapted to our base length.
- Linting should use the minimal number of third-party tools where possible, flag and new additions. (eg: `clang-tidy`)
- Use public (`Conan`?) releases for CI deps (+ CI cache) or other `CMake` native solutions

## Out of scope

- Windows or macOS CMake builds
- Wheels and other such distributable artifacts
- `setup.py` calling `CMake` from `pip install`, can just use `ctest`

**Comment by foundrytom** [comment]
We need to work towards https://bestpractices.coreinfrastructure.org/en

**Comment by TheRealJokerMan** [comment]
Where applicable, have you considered just utilising CMake's [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html) to pull lightweight CMake-based projects?

**Comment by foundrytom** [comment]
@feltech Updated the ACs to capture our earlier selection of the `Google` preset for `clang-format`

**Comment by foundry-markf** [comment]
Note this CMake open issue https://gitlab.kitware.com/cmake/cmake/-/issues/8438 

> Currently, add_dependencies can not be used to create a dependency if one of the specified targets is a cmake "build-in" target, like "test", "install" or "all".

So anything doing this works by luck it seems.

**Comment by foundrytom** [comment]
Closing, as #251 will cover remanning tasks at our leisure.
