### ISSUE TITLE
RFC 11: `Specification` implementation design proposal

### ISSUE THREAD

**Issue by foundrytom** [TheFoundryVisionmongers/OpenAssetIO#245]
# Specification design proposal

_Specifications_ are logically composed of a set of _traits_. Each trait has a unique name and a set of _properties_, where each property is optional (i.e. "unset" is a valid state).

We reviewed several options for potential specification data structures, including

* Classic C++ class composed of traits objects as members.
* Classic C++ class with multiple inheritance of traits classes.
* Wrapped dictionary with string property access and (mostly) run-time and (some) compile-time checks/optimisations.
* Wrapped dictionary with "views" on subsets of properties as trait member functions.

The final option was selected for further development, since it meets the following design goals naturally.

### Extensible

_Definable out of core (by host integrations/managers)_

A dictionary type means that wrappers can be created at any point in almost any language. For example, JSON schemas could be used to automatically generate wrapper classes for any language. In addition, there is no runtime requirement for these wrappers to be present in order to pass the underlying data, without loss, through the system.

### Hierarchical/Composable

_To support "upcasting" to known specifications or traits_

Applying a view on a dictionary is synonymous with upcasting.

### Simple in structure

_To simple data types for interop/serialisation_

Dictionaries of primitive types are trivially serializable and are
common in many languages.

### Robust

_Compile-time checks for programming errors - property access or invalid method arguments_

Once a view is applied to a dictionary, then property access should be through concrete accessor/mutator methods on the view class, removing a class of programmer error. Such methods can additionally implement validation beyond compiler/static analysis checks.

### Discoverable

_Runtime introspection/help_

A simple dictionary type is naturally amenable to runtime introspection. A (JSON) schema could provide another reference point for developer help.

Trait/specification wrapper classes can additionally provide methods that return details of their supported properties.

## Prototype

A notional prototype implementation was created, usage of which is summarised below.

Implementation notes:

* The dictionary is a C++ `std::unordered_map` with `std::string` keys and `std::variant` values that store a `std::optional` wrapper around a primitive type (hence in the snippet below `property::Bool` is a `std::optional<bool>`). One tweak could be to remove `std::optional`  and instead remove elements from the dictionary to signify "unset".
* `BaseSpecification` wraps the dictionary and has a number of `virtual` methods defining the specification interface, but provides no validation on its own.
* `ConcreteSpecification` is a template class that uses multiple inheritance to mix in traits (and has some compile-time niceties).

```c++
// .hpp

struct NukeTrait : BaseTrait<NukeTrait> {
  static constexpr std::string_view kName = "nuke";

  property::Bool getUsesNukeX() const;
  void setUsesNukeX(property::Bool value);
};

struct FileTrait : BaseTrait<FileTrait> {
  static constexpr std::string_view kName = "file";

  property::Bool getIsBig() const;
  void setIsBig(property::Bool value);
};

struct NukeScriptSpecification 
    : ConcreteSpecification<NukeTrait, FileTrait> {
    
  using ConcreteSpecification<NukeTrait, FileTrait>::
      ConcreteSpecification;
};

// .cpp

property::Bool NukeTrait::getUsesNukeX() const { 
  return getProperty<property::Bool>("usesNukeX"); 
}
void NukeTrait::setUsesNukeX(property::Bool value) { 
  setProperty("usesNukeX", value); 
}

property::Bool FileTrait::getIsBig() const { 
  return getProperty<property::Bool>("isBig"); 
}
void FileTrait::setIsBig(property::Bool value) { 
  setProperty("isBig", value); 
}

// Usage

void doWork(BaseSpecification& spec) {
  // Naively: check if `spec` has "file" trait and do some work if so.
  //  Note: may throw an exception if the dict doesn't have the value.

  if (static_cast<bool>(spec.dict->count("file"))) {
    std::cout << "isBig = "
              << std::get<property::Bool>(
                  spec.dict->at("file").at("isBig")).value_or(false)
              << std::endl;
  }

  // Alternatively: apply a "view" of the trait to the specification's
  // dictionary.

  if (spec.hasTrait("file")) {
    FileTrait const fileTraitView{spec.dict};
    
    std::cout << "isBig = " 
              << fileTraitView.getIsBig().value_or(false) 
              << std::endl;
  }
}
```

### C interface

A C API operating on an opaque handle to a specification dictionary should be straightforward, for example

```c
extern "C"
{
typedef int ErrorCode;
typedef char[500] ErrorMessage;

/**
 * Get an integer property from a specification dictionary. 
 */
ErrorCode openassetio_Specification_getProperty_i(
    ErrorMessage err, bool* outIsSet, int* outValue,,
    SpecificationHandle handle,
    char const* traitName, char const* propertyName) {
    
  auto spec = reinterpret_cast<BaseSpecification*>(handle);
  
  property::Value prop;
      
  try {
    prop = spec.dict->at(traitName).at(propertyName);
    
  } catch (std::out_of_range const& ex) {
    *outIsSet = false;
    return 0;
    
  } catch (std::exception const& ex) {
    strncpy(err, ex.what(), sizeof(ErrorMessage)-1);
    err[sizeof(ErrorMessage)-1] = '\0';
    return 1;
  }
  
  try {
    auto const propAsInt = std::get<property::Int>(prop);
    
    if (!propAsInt.has_value()) {
      *outIsSet = false;
      return 0;
    }
    
    *outIsSet = true;
    *outValue = *propAsInt;
    return 0;
        
  } catch (std::exception const& ex) {
    strncpy(err, ex.what(), sizeof(ErrorMessage)-1);
    err[sizeof(ErrorMessage)-1] = '\0';
    return 1;
  }
}
}
```

Similar methods would have to be constructed for each possible primitive value type (`bool`, `int`, `double`, `string`), and a slightly more complex variant would be required for the (`string` -> primitive) dictionary value type. 

#### Language bindings

We don't expect the C API to require much validation code in itself (e.g ensuring a trait supports the given property key before querying) since we expect the C API to be an interface for higher-level languages that will provide their own wrappers implementing validation at run-time or via a strongly typed interface.

**Comment by foundrytom** [comment]
@feltech also found https://app.quicktype.io/, which could be a great candidate for the autogeneration of language specific implementations from a simple, common definition.

**Comment by TheRealJokerMan** [comment]
Regarding the use of `strncpy`, does that compile cleanly under /W4 on Win32 or is `_CRT_SECURE_NO_WARNINGS` required?

Also, the use of a single, fixed-size buffer to store the exception message worries me a little: is this C-API explicitly single-threaded; what happens if the exception message is greater than 500 characters?

**Comment by feltech** [comment]
> Forgive my ignorance here if I have things muddled, a question re:
> 
> > // Better: upcast to the trait class.
> 
> Is the difference between this, and the alternate view application approach, that the upcast requires a runtime registry of factory functions to trait collections? So that during deserialization, the deserialization code can instantiate the correct `ConcreteSpecification` so that the `dynamic_cast` works?

Yes indeed, if the specification/trait collection has come from a deserialisation then some kind of registry is required.

> Is a benefit of the view-based approach that in theory, the registry isn't needed as it is just the domain specific consuming code that has to know what view it wants, rather than the generic core API layer that might be handling the deserialisation?

Yeah that's a big advantage. Perhaps the specification/trait collection class only really needs `hasTrait`. 

In the prototype the default implementation of `hasTrait` simply checks the top-level keys of the underlying dict. `ConcreteSpecification`s can be a little faster by scanning through the (`BaseTrait`) base class's identifiers, and even more optimised if you can upcast to the original class and use `hasStaticTrait`, which is entirely compile-time.

Having said that, for the most general case, perhaps trying to be clever with the specification/trait collection is just not worthwhile and it should just be (a lightweight wrapper around) a dict, with all access/mutation done by trait views (or rarely, directly to the dict).

I don't think we have a use case where the same set of traits could have different behaviour if wrapped in a different specification?  Or even that specifications provide any real functionality beyond holding traits?

**Comment by feltech** [comment]
> Regarding the use of `strncpy`, does that compile cleanly under /W4 on Win32 or is `_CRT_SECURE_NO_WARNINGS` required?

I've not checked Windows.  I guess ideally we'd `#ifdef` to use `strncpy_s` (or whatever) if available.  I couldn't find a cross-platform safe `strcpy` in the standard library.
 
> Also, the use of a single, fixed-size buffer to store the exception message worries me a little: is this C-API explicitly single-threaded; what happens if the exception message is greater than 500 characters?

An alternative would be to accept an arbitrary `char*` along with a max size.  It's just convenient to have a fixed-size array, to reduce boilerplate all round.  Indeed any error message that's too long will get cut off.

**Comment by foundrytom** [comment]
Thanks for filling in the gaps @feltech.

> Yeah that's a big advantage. Perhaps the specification/trait collection class only really needs `hasTrait`.

Keeping it simpler and avoiding a runtime registry would certainly be a good thing. If we really found a use for it, it is something that we could add later without any consequences right?

> In the prototype the default implementation of `hasTrait` simply checks the top-level keys of the underlying dict. `ConcreteSpecification`s can be a little faster by scanning through the (`BaseTrait`) base class's identifiers, and even more optimised if you can upcast to the original class and use `hasStaticTrait`, which is entirely compile-time.

I'm not sure we'll ever be able to be entirely compile time as any given host/manager code will never be able to see the code that creates the spec/trait in the first place? We'd only be compile time post `dynamic_cast` as the entry point to any method that considers a spec only ever sees one of the bases?

> Having said that, for the most general case, perhaps trying to be clever with the specification/trait collection is just not worthwhile and it should just be (a lightweight wrapper around) a dict, with all access/mutation done by trait views (or rarely, directly to the dict).

Is the main Q then perhaps more one around #247 - in how would the specifics of this implementation affect removing `resolveEntityReference`, and relying on essentially `return resolve(ref, BlobTrait.kName, context)[BlobTrait.kName][BlobTrait.kUrl]`, in terms of the overhead of resolving a million references?

All of this may be more costly, but if in practice that cost is always dwarfed by any real-world implementation, we could be ok. I'd take a punt that trying to make hosts batch resolves would be better way to ensure resolving doesn't slow down scene expansion in real world scenarios where resolve is backed by a service-backed system.

That being said though, we definitely have to make sure that the API is as thin as possible, for any given scenario where a manager already has an in-process, in-memory cached answer to any resolution.

> I don't think we have a use case where the same set of traits could have different behaviour if wrapped in a different specification? Or even that specifications provide any real functionality beyond holding traits?

No, I think by design, they should never vary, as they're meant to be the formal definition of a well known, concrete set of fields.

**Comment by feltech** [comment]
> Thanks for filling in the gaps @feltech.
> 
> > Yeah that's a big advantage. Perhaps the specification/trait collection class only really needs `hasTrait`.
> 
> Keeping it simpler and avoiding a runtime registry would certainly be a good thing. If we really found a use for it, it is something that we could add later without any consequences right?

I agree that avoiding a registry would be ideal and could be added later if necessary.
 
> > In the prototype the default implementation of `hasTrait` simply checks the top-level keys of the underlying dict. `ConcreteSpecification`s can be a little faster by scanning through the (`BaseTrait`) base class's identifiers, and even more optimised if you can upcast to the original class and use `hasStaticTrait`, which is entirely compile-time.
> 
> I'm not sure we'll ever be able to be entirely compile time as any given host/manager code will never be able to see the code that creates the spec/trait in the first place? We'd only be compile time post `dynamic_cast` as the entry point to any method that considers a spec only ever sees one of the bases?

I agree it looks like compile-time niceties would be rare, if ever, in normal usage. For the `hasStaticTrait` example to work, the specification would have to be downcasted to the most-derived type, which would need some kind of registry, either implicit (a big if-else statement) or explicit as an openassetio feature.

> > Having said that, for the most general case, perhaps trying to be clever with the specification/trait collection is just not worthwhile and it should just be (a lightweight wrapper around) a dict, with all access/mutation done by trait views (or rarely, directly to the dict).
> 
> Is the main Q then perhaps more one around #247 - in how would the specifics of this implementation affect removing `resolveEntityReference`, and relying on essentially `return resolve(ref, BlobTrait.kName, context)[BlobTrait.kName][BlobTrait.kUrl]`, in terms of the overhead of resolving a million references?

Another possibly is to bake into the trait class so `return BlobTrait::fromEntityReference(ref).getUrl()`.

> All of this may be more costly, but if in practice that cost is always dwarfed by any real-world implementation, we could be ok. I'd take a punt that trying to make hosts batch resolves would be better way to ensure resolving doesn't slow down scene expansion in real world scenarios where resolve is backed by a service-backed system.

There are other low-level tweaks we can add to squeeze out better performance, either by using a more optimal dictionary library or by tweaking the parameters to the std library (e.g. `reserve`ing the space required for properties, tweaking the bucket count, etc)

**Comment by foundrytom** [comment]
> > Keeping it simpler and avoiding a runtime registry would certainly be a good thing. If we really found a use for it, it is something that we could add later without any consequences right?
> 
> I agree that avoiding a registry would be ideal and could be added later if necessary.

Is it worth removing the middle cast based option from the illustration, and we can call #226 done?

**Comment by feltech** [comment]
> Is it worth removing the middle cast based option from the illustration, and we can call #226 done?

Edited the proposal (also added missing `return` in the C implementation)

**Comment by foundrytom** [comment]
Closing issue as high-level approach ratified, and work under way in #255.
