### ISSUE TITLE
Is `resolveEntityReference` still relevant?

### ISSUE THREAD

**Issue by foundrytom** [TheFoundryVisionmongers/OpenAssetIO#247]
## What

Decide if `manager.resolveEntityReference(ref)` is meaningful or it could simply be `manager.entityData(ref, BlobTrait)`, where `BlobTrait ` defines a `url` property.

## Why

#238 resolves one of the lingering messy parts of the current API design. The spec hierarchy precluded the ability to define concrete, well known behaviour that was shared across branches in the spec tree. This meant Specifications could never be used to reliably define any particular aspect of an entity in isolation. This predicated methods such as `resolveEntityReference` in order to formalise a common shared behaviour of "resolving to a string".

Being able to concretely ask for specific data from an entity simplifies many aspects of the conceptual model, and removes the baked-in concept of a string-to-string mapping as a core premise. 

This already caused us issues with "non file based entities" where there may be no specific primary string. The name "primary string" itself shows the problem - that is, it is unspecific and leaves a lot to interpretation. This all goes away.

This could have performance implications though for the primary (current) use case of resolving paths? There should be no reason not to intern all spec/trait magic strings though I think?

If we do this, then it most certainly means that #31 should be `manager.entityTraits(ref, context)`, that returns the collection of trait names that the entity supports.

This change has the additional benefit that it encourages a formal definition of any well-known traits that hosts or managers may wish to use within the system, something lost with the old attributes free-for-all bucket.

### Potential downsides

A potential issue with this approach of a host specifying it's intended usage by requesting a specific trait is that you would need a "default" trait that a generic resolver with no knowledge of usage could use to 'resolve a ref to any old string'. 

This raises the question though - is the idea of "blind resolving" compatible with the overarching principal in this API of providing contextual information about the use of the data?

If such a behaviour was required, one way to achieve this could be to simply define a `string` trait, with a `value` property, and use `entityData(ref, StringTrait)`, which effectively models the behaviour of `resolveEntityReference`:

```python
def resolveEntityReference(self, ref, context):
    return StringTrait(self.entityData(ref, StringTrait.name, context)).getValue()
```

## ACs

- A decision on whether this is a sensible change.
- Documentation of the proposed API changes.
- A qualitative performance comparison against some naive manager implementation, that has the data for a `BlobTrait`  in memory that shows, the comparative cost of resolving 1,000,000 unique references in terms of the differences in:
   - Total wall-clock time.
   - CPU Time spent in the API (not including the internal cost of looking up the resolved data in the manager).
   - Portion of API time spent in memory allocations.

## Sketch

Assuming:
```cpp
trait EntityTrait {
    name: "entity"
}

trait BlobTrait {
    name: "blob",
    props: { url: str, mimeType: str }
}

trait ImageTrait {
    name: "image",
    props: { colorSpace: str }
}

spec ImageSpec {
    traits: ["entity", "blob", "image"]
}
```

### Publishing an image
A host wishes to publish an image to a target entity reference, ensuring its color space is properly tracked.

```python
img = ImageSpec()
img.blobTrait().setUrl("file:///some/render.exr")
img.imageTrait().setColorSpace("ACES - ACES2065-1")

context.access = context.kWrite
published_ref = manager.register(ref, img, context)
```

### Simple resolve only
A generic script handling bulk resolution of references to data URLs.
 
```python
context.access = context.kRead
url = manager.entityData(ref, ['blob'], context)['blob']['url']
```

### More data in one call
A compositing application wanting to load an image with the correct colorspace.
```python
context.access = context.kRead

img_data = manager.entityData(ref, [BlobTrait.name, ImageTrait.name], context)

path = BlobTrait(img_data).getUrl()
colorspace = ImageTrait(img_data).getColorSpace()
```
or
```python
context.access = context.kRead

img_data = manager.entityData(ref, ImageSpec.traitNames, context)

img = ImageSpec(img_data)
url = img.blobTrait().getUrl()
colorspace = img.imageTrait().getColorSpace()
```
The first example has the advantage of only requesting data that is explicitly required. The second, may fetch more data than is necessary, depending on exactly which traits the spec used composes.

Note however, that in either case, this is one less API call than the current implementation that would required a call to `resolveEntityReference` _then_ `getEntityAttributes`.

### Browsing
A compositing application wanting to browse for ACES colorspace images only.
Note: this is not affected by these changes, but illustrates the symmetry.
```python
widget = ui_delegate.getWidget(kEntityBrowserIdentifier, context)

required_spec = ImageSpec()
required_spec.imageTrait().setColorSpace("ACES - ACES2065-1")
context.access = context.kReadMultiple

refs = widget.browse(required_spec, context)
```
The above uses a spec over just `ImageTrait`, as the other traits of `ImageSpec` (`entity` and `blob`) are also essential to subsequent operations.

**Comment by foundrytom** [comment]
.. alternatively, we could just call it `manager.resolve(ref, traitNames, context)` and get rid of `entityAttributes` 🙃

**Comment by feltech** [comment]
> It'd be nice it we _didnt_ ever end up needing it to be magical as it makes life easier for the manager...

Agreed.  Maybe we try going with the assumption that we don't need a generic `StringTrait` that can map to multiple things depending on the context.  Seems easy enough to add later.

**Comment by feltech** [comment]
On re-thinking/re-reading this issue, I just want to second the AC for performance comparison.  

I recall previous conversations about critical paths for performance, and IIRC the only example is the "resolving thousands of references to their primary string" case.  So it may be that we need a special case just for this, where we forego specifications/traits/dictionaries (or it may be that the difference in negligible in practice).

Are there other foreseeable bulk queries that must be performant?

**Comment by foundrytom** [comment]
> Are there other foreseeable bulk queries that must be performant?

I don't believe there are any in the the current API that we know of today.

An interesting side thought on this, is that would actually batching queries, vs individual lookups totally eclipse the benefits any specific fast-path API call?

It would be interesting to find out, in the happy fast path, for these high-volume resolves, how many hit a cache in such a way that the `C++` overhead would eclipse the cost of actually resolving?

In that, we've heard anecdotally that some people are stalling + batching up resolves in their USD AR 2 resolver to avoid the individual back-end query latency slowing everything. 

I believe its a side effect of the (loosely) BFS that most scene expansion algorithms go for that means batching would required a shift in approach on the host side?

**Comment by foundrytom** [comment]
Closing as we have decided to switch to the unified model (see #269), work planned.
