### ISSUE TITLE
Migrate manager `identifier`/`displayName` (solve static identifier -> pure virtual)

### ISSUE THREAD

**Issue by feltech** [TheFoundryVisionmongers/OpenAssetIO#289]
# What

Add `identifier` and `displayName` methods to the C++ `ManagerInterface` and inherit their default implementations in Python.

# Why

This is a necessary step toward a C++ manager plugin and a C++->Python bridge.

# Acceptance criteria

* C++ `ManagerInterface` class has pure virtual `identifier` and `displayName`  methods with signature matching existing Python methods.
* Python `ManagerInterface` bound to trampoline class such that calling `identifier` or `displayName` when not overridden by the Python subclass will trigger a pybind exception.
* Example plugins updated to no longer rely on static `identifier` method.
* Docstrings migrated to C++ (OK to leave Python docstrings empty/default).
* C API for `ManagerInterface` handles,  `identifier` and `displayName`.

# Implementation notes

* Example plugin `ManagerPlugin` classes hardcode the identifier.  This is duplication, but more readable as a simple example.

# Tasks

- [x] #292
- [x] C/C++ test harness investigation spike: #196
- [x] #293
- [x] #294

**Comment by foundrytom** [comment]
We'll need to revert https://github.com/TheFoundryVisionmongers/OpenAssetIO/pull/125 for `ManagerInterface`. Lol.
