### ISSUE TITLE
Remove `thumbnailSpecification`

### ISSUE THREAD

**Issue by feltech** [TheFoundryVisionmongers/OpenAssetIO#86]
# What

Handle thumbnails for entities generically, rather than through the existing special-case of the `thumbnailSpecification` API.

# Why

Currently we have a special case to handle thumbnails, whereby all `EntitySpecification`s include a `thumbnailPath` attribute, so that when `register`ing an entity the manager can also pull in the thumbnail.  

In order to determine whether the manager wants a thumbnail, and if so what are the desired attributes (e.g. width and height), `thumbnailSpecification` must be called by the host, passing the `Specification` of the entity that is about to be published.

However, we probably already have mechanisms of accomplishing these steps in a generic way.  One proposal could be

* Add a `kWantsThumbnail` bit to the `managementPolicy`, to determine if the `Specification` of the target entity that is about to be published also needs a thumbnail.
* `preflight` the target entity, passing a `ThumbnailSpecification`. The return value of `preflight` is then the writeable entity reference for the thumbnail, say `thumbnailRef`.
* Get the required thumbnail properties via `entityAttributes([thumbnailRef], ["thumbnailWidth", "thumbnailHeight", ...], ...)` (based on previous discussion of how we would like to redesign `getEntityMetadata`)
* Write the thumbnail to the path returned by `resolveEntityReference([thumbnailRef], ...)`
* `register` the thumbnail.

**Comment by foundrytom** [comment]
This also has the added benefit that the mechanism is truly bi-directional. The host uses the standard publishing semantic to register a thumbnail, but can also use the standard `getRelatedReferences` mechanism with a `ThumbnailSpecification` to request a thumbnail from the manager for any given entity.
